


DROP TABLE IF EXISTS LOAN_DATA;
CREATE TABLE LOAN_DATA(
REPRICING_DATE DATE DEFAULT NULL
,ENTITY_CODE VARCHAR(20) DEFAULT 'SG01'
,ACCT_CUSTOMER_ROLE VARCHAR(30) DEFAULT 'PRIMARY'
,PROJ_FIN_COUNTRY_CODE VARCHAR(2) DEFAULT ''
,PROJ_FIN_SUB_SECTOR VARCHAR(60) DEFAULT ''
,UNCONDITIONAL_CANCEL_IND CHAR(1) DEFAULT 'Y'
,UNSECURED_IND CHAR(1) DEFAULT 'Y'
,ORIG_LTV DECIMAL(18,2) DEFAULT NULL 
,CURR_LTV DECIMAL(18,2) DEFAULT NULL
,INTEREST_RATE_TYPE VARCHAR(60) DEFAULT ''
,BRANCH_ID VARCHAR(20)  DEFAULT ''
,DATA_SOURCE VARCHAR(20) DEFAULT 'Salesforce_CL_Loan'
,IMPAIRMENT_STATUS_IND CHAR(1)  DEFAULT ''
,RESTRUCTURED_IND CHAR(1)  DEFAULT 'N'
,LOAN_PURPOSE_TYPE VARCHAR(20) DEFAULT ''
,SYNDICATED_AMT DECIMAL(18,2) DEFAULT NULL
,SYNDICATED_IND CHAR(1) DEFAULT ''
,ACT_LEAD_ARRANGER_IND CHAR(1)  DEFAULT ''
,LEAD_ARRANGER_AMT DECIMAL(18,2)  DEFAULT NULL
,IFRS9_CLASS_TYPE VARCHAR(20) DEFAULT 'AC'
,ULTIMATE_RISK_CPRT VARCHAR(25)  DEFAULT ''
,FAIRVALUE_HIER VARCHAR(20) DEFAULT ''
,BOOK_TYPE CHAR(1) DEFAULT 'B'
,INT_RATE_SENSITIVE_IND CHAR(1) DEFAULT 'Y'
,PLEDGED_AMT DECIMAL(18,2)  DEFAULT NULL
,FORECLOSED_IND CHAR(1) DEFAULT ''
,transactor_ind CHAR(1) DEFAULT 'N'
,FREE_CREDIT_BALANCE_AMT DECIMAL(18,2)  DEFAULT NULL
,INTEREST_CHARGES DECIMAL(18,2) DEFAULT 0.00
,BANK_CHARGES DECIMAL(18,2) DEFAULT 0.00
,LATE_PAYMENT_CHARGES DECIMAL(18,2) DEFAULT NULL
,ACTION_INITIATED_IND CHAR(1) DEFAULT ''
,ACTION_INITIATED_TYPE VARCHAR(50) DEFAULT ''
,TRANSITIONAL_ARRANGEMENT_IND CHAR(1) DEFAULT ''
,WRITEOFF_DATE DATE DEFAULT NULL
,TOT_WRITEOFF_QTD DECIMAL(18,2) DEFAULT NULL
,ACCOUNT_WRITEOFF_IND CHAR(1) DEFAULT ''
,SUSPENSION_IND CHAR(1) DEFAULT ''
,GEN_ALLOWANCE_AMT DECIMAL(18,2) DEFAULT NULL
,BANK_ASSET_CLASS_CODE VARCHAR(20) DEFAULT ''
,MARKET_VALUE DECIMAL(18,2) DEFAULT NULL
,EXP_REVOLVING_IND CHAR(1) DEFAULT ''
,CHANNEL_TYPE VARCHAR(30) DEFAULT ''
,MATERIALITY_THRESHOLD DECIMAL(18,2) DEFAULT 5000000
,NOMINAL_THRESHOLD DECIMAL(18,2) DEFAULT 0.00
,ENCUMBRANCE_STATUS_IND CHAR(1) DEFAULT ''
,POCI_IND CHAR(1) DEFAULT ''
,GL_DEPARTMENT VARCHAR(20) DEFAULT '241110'
,GL_LOB VARCHAR(20) DEFAULT '110'
,GL_LOCATION VARCHAR(20) DEFAULT '1100'
,GL_INTERCOMPANY VARCHAR(20) DEFAULT '9999'
,GL_PRODUCT VARCHAR(20) DEFAULT ''
,GL_CUSTOMER_SEGMENT VARCHAR(20) DEFAULT ''
,GL_FUTURE1 VARCHAR(20) DEFAULT '999'
,GL_FUTURE2 VARCHAR(20) DEFAULT '999999'
,UNUSED_LIMIT DECIMAL(18,2) DEFAULT 0
,JUNIOR_CHARGE_IND CHAR(1) DEFAULT ''
,EXPOSURE_ID VARCHAR(50) DEFAULT ''
,REPORTING_DATE DATE DEFAULT NULL
,CUSTOMER_ID VARCHAR(20) DEFAULT ''
,FACILITY_ID VARCHAR(20) DEFAULT ''
,EXPOSURE_START_DATE DATE DEFAULT NULL
,NEXT_PAYMENT_DATE DATE DEFAULT NULL
,BANK_PRODUCT_CODE VARCHAR(20) DEFAULT 'SMEL'
,TXN_CCY_CODE VARCHAR(3) DEFAULT ''
,COUNTRY_CODE VARCHAR(2) DEFAULT 'SG'
,EXPOSURE_END_DATE DATE DEFAULT NULL
,PAST_DUE_DATE DATE DEFAULT NULL
,PAST_DUE_IND CHAR(1) DEFAULT ''
,SANCTIONED_LIMIT  DECIMAL(18,2) DEFAULT NULL
,PRIN_OUTSTANDING_AMT DECIMAL(18,2) DEFAULT NULL
,INTEREST_OUTSTANDING_AMT DECIMAL(18,2) DEFAULT NULL
,GROSS_OUTSTANDING_AMT  DECIMAL(18,2) DEFAULT NULL
,UNDRAWN_AMT DECIMAL(18,2) DEFAULT NULL
,INTEREST_RATE DECIMAL(18,2) DEFAULT NULL
,DEFAULTED_IND CHAR(1) DEFAULT ''
,RESTRUCTURED_DATE DATE DEFAULT NULL
,EXTENDED_CREDIT_FAC_IND CHAR(1) DEFAULT ''
,DAYS_PAST_DUE INT DEFAULT NULL
,ULTIMATE_RISK_COUNTRY VARCHAR(2)  DEFAULT 'SG'
,ORIGINAL_INTEREST_RATE DECIMAL(18,2) DEFAULT NULL
,RESIDUAL_MATURITY_DAYS INT DEFAULT NULL
,INTEREST_BEARING_BALANCE_AMT DECIMAL(18,2) DEFAULT NULL
,AGE_IN_DAYS BIGINT DEFAULT NULL
,WRITEOFF_AMT DECIMAL(18,2) DEFAULT NULL
,ACCOUNT_MAS635_IND CHAR(1) DEFAULT ''
,LAST_PAYMENT_DATE DATE DEFAULT NULL
,ACCT_STATUS_CODE VARCHAR(100) DEFAULT ''
,ACCT_STATUS_DATE DATE DEFAULT NULL
,GL_ID VARCHAR(20) DEFAULT ''
,CUSTOMER_MONTH_ON_BOOK BIGINT DEFAULT NULL
,EMI  DECIMAL(18,2) DEFAULT NULL
,DRAWN_AMT DECIMAL(18,2) DEFAULT NULL
,MAS612_QUALITATIVE_CRITERIA VARCHAR(20) DEFAULT ''
,HIGH_DPD_CBS_IND CHAR(1) DEFAULT ''
,MINIMUM_PAYMENT_IND CHAR(1) DEFAULT ''
,CUSTOMER_DAYS_PAST_DUE BIGINT DEFAULT NULL
,DPD_COUNT_EXCEEDED BOOLEAN DEFAULT NULL
,HAS_ACCELERATED_LOANS CHAR(1) DEFAULT ''
,INDEFINITE_BLOCK_DPD_COUNT_EXCEEDED BOOLEAN DEFAULT NULL
,SUSPENDED_BTI_FLAG CHAR(1) DEFAULT ''
,CBS_CUO DECIMAL(18,2) DEFAULT NULL
,EFFECTIVE_INTEREST_RATE DECIMAL(18,2) DEFAULT NULL
,UPFRONT_PROCESSING_FEE DECIMAL(18,2) DEFAULT NULL
,UPFRONT_UNAMORTIZE_FEE DECIMAL(18,2) DEFAULT NULL
,ACCT_BLOCK_CODE VARCHAR(100) DEFAULT ''
,BANK_SUB_PRODUCT_CODE VARCHAR(100) DEFAULT ''
,CONVERSION_TYPE VARCHAR(100) DEFAULT ''
,MonthOfImport VARCHAR(10) NOT NULL
);

CREATE INDEX IDX_EXPOSURE_ID ON LOAN_DATA(EXPOSURE_ID);
CREATE INDEX IDX_CUSTOMER_ID ON LOAN_DATA(CUSTOMER_ID);
CREATE INDEX IDX_FACILITY_ID ON LOAN_DATA(FACILITY_ID);
CREATE INDEX IDX_BANK_SUB_PRODUCT_CODE ON LOAN_DATA(BANK_SUB_PRODUCT_CODE);
 
DROP VIEW IF EXISTS v_CustomerLookup;
CREATE VIEW v_CustomerLookup AS
WITH CTE AS (
SELECT DISTINCT A.User_ID__c ,L.SSIC_Code ,L.GL_Customer_Type_Code,ROW_NUMBER() OVER (PARTITION BY A.User_ID__c ORDER BY P.CreatedDate DESC) RNK
FROM NS_Account A
JOIN NS_loan__Loan_Account__c LLA ON A.Id=LLA.loan__Account__c AND LLA.GXS_Book__c=TRUE
LEFT JOIN NS_genesis__Applications__c P ON P.genesis__Account__c=A.Id AND P.Loan_ID__c IS NULL AND P.genesis__Loan_Amount__c IS NOT NULL AND P.genesis__Status__c='Approved' AND P.SSIC_Code__c IS NOT NULL
LEFT JOIN NS_Account PA ON PA.ID=A.PARENTID 
LEFT JOIN Lookup L ON L.SSIC_Code=A.SSIC_Code
LEFT JOIN (SELECT DISTINCT  SSIC__c,Description__c FROM NS_Principal_Activity_Activities__c ) PAA ON PAA.SSIC__c=P.SSIC_Code__c
WHERE LEFT(A.User_ID__c,1)='2' AND LLA.loan__Loan_Status__c like 'Active%'
AND LLA.Genesis_Product__c NOT IN ('Term LN - Variable Rate - Monthly')
) SELECT * FROM CTE WHERE RNK=1 and SSIC_Code IS NOT NULL;


DROP VIEW IF EXISTS v_ChildLoan_1;
CREATE VIEW v_ChildLoan_1 AS
SELECT DISTINCT 
	REPRICING_DATE
	,INTEREST_RATE_TYPE
	,ORIG_LTV
	,CURR_LTV
	,IMPAIRMENT_STATUS_IND
	,LOAN_PURPOSE_TYPE
	,ULTIMATE_RISK_CPRT
	,LATE_PAYMENT_CHARGES
	,WRITEOFF_DATE
	,TOT_WRITEOFF_QTD
	,ACCOUNT_WRITEOFF_IND
	,CHANNEL_TYPE
	,GL_PRODUCT
	,GL_CUSTOMER_SEGMENT
	,EXPOSURE_ID
	,REPORTING_DATE
	,CUSTOMER_ID
	,FACILITY_ID
	,EXPOSURE_START_DATE
	,NEXT_PAYMENT_DATE
	,TXN_CCY_CODE
	,EXPOSURE_END_DATE
	,PAST_DUE_DATE
	,PAST_DUE_IND
	,PRIN_OUTSTANDING_AMT
	,INTEREST_OUTSTANDING_AMT
	,GROSS_OUTSTANDING_AMT
	,INTEREST_RATE
	,DEFAULTED_IND
	,DAYS_PAST_DUE
	,ORIGINAL_INTEREST_RATE
	,RESIDUAL_MATURITY_DAYS
	,INTEREST_BEARING_BALANCE_AMT
	,WRITEOFF_AMT
	,LAST_PAYMENT_DATE
	,ACCT_STATUS_CODE
	,CUSTOMER_MONTH_ON_BOOK
	,EMI
	,DRAWN_AMT
	,MAS612_QUALITATIVE_CRITERIA
	,EFFECTIVE_INTEREST_RATE
	,CUSTOMER_DAYS_PAST_DUE
	,AGE_IN_DAYS
	,UPFRONT_PROCESSING_FEE
	,ACCT_BLOCK_CODE
	,BANK_SUB_PRODUCT_CODE
	,GL_ID
	,BANK_ASSET_CLASS_CODE
	,EXP_REVOLVING_IND
	,HIGH_DPD_CBS_IND
	,Product_Code__c
	,Application_Approved_Date__c
	,MonthOfImport
FROM (
SELECT DISTINCT 
CASE WHEN LLA.loan__Interest_Type__c ='Floating' THEN LLA.loan__Floating_Rate_Revision_Date__c ELSE LLA.loan__Last_Installment_Date__c  END AS REPRICING_DATE
,CASE WHEN LLA.loan__Interest_Type__c ='Floating' THEN 'VAR_TYPE' ELSE 'FIX_TYPE' END AS INTEREST_RATE_TYPE
,GA.Percentage_Of_Financed__c AS ORIG_LTV
,GA.Percentage_Of_Financed__c AS CURR_LTV
,CASE WHEN A.Credit_Grade__c IN ('SS','DFL','L') THEN 'Y' ELSE 'N' END AS IMPAIRMENT_STATUS_IND
,CASE WHEN P.genesis__CL_Product_Name__c IN ('Working Capital Financing','NIP WC Bullet','Term LN - Citi(Monthly)','Overdraft LN - Citi(Single)') THEN 'OTH' ELSE 'TF' END AS LOAN_PURPOSE_TYPE
,A.Legal_Entity_Type AS ULTIMATE_RISK_CPRT
,LLA.loan__Fees_Remaining__c + LLA.loan__Fees_Paid__c AS LATE_PAYMENT_CHARGES
,CASE WHEN LLA.Loan__Loan_Status__c='Closed- Written Off' THEN LLA.loan__Charged_Off_Date__c ELSE NULL END AS WRITEOFF_DATE
,CASE WHEN LLA.loan__Loan_Status__c='Closed- Written Off' THEN LLA.loan__Charged_Off_Principal__c + LLA.loan__Charged_Off_Interest__c + LLA.loan__Charged_Off_Fees__c ELSE 0 END AS TOT_WRITEOFF_QTD
,CASE WHEN LLA.Loan__Loan_Status__c='Closed- Written Off' THEN 'Y' ELSE 'N' END AS ACCOUNT_WRITEOFF_IND
,P.Channel__c AS CHANNEL_TYPE
,CASE WHEN P.genesis__CL_Product_Name__c IN ('Working Capital Financing','NIP WC Bullet','Term LN - Citi(Monthly)','Overdraft LN - Citi(Single)') THEN '110230' ELSE '111400' END AS GL_PRODUCT
,CL.GL_Customer_Type_Code AS GL_CUSTOMER_SEGMENT
,LLA.Loan_App_ID__c AS EXPOSURE_ID
,DATE(NOW() - INTERVAL 1 DAY) AS REPORTING_DATE
,A.User_ID__c AS CUSTOMER_ID
,P.Name AS FACILITY_ID
,LLA.loan__Disbursal_Date__c AS EXPOSURE_START_DATE
,CASE WHEN YEAR(LLA.loan__Next_Installment_Date__c)=3000 THEN LLA.loan__Last_Installment_Date__c ELSE LLA.loan__Next_Installment_Date__c END AS NEXT_PAYMENT_DATE
,LLA.Currency__c AS TXN_CCY_CODE
,LLA.loan__Last_Installment_Date__c AS EXPOSURE_END_DATE
,CASE WHEN LLA.DPD_no_grace_period__c >0 THEN LLA.loan__Oldest_Due_Date__c ELSE NULL END PAST_DUE_DATE
,CASE WHEN LLA.DPD_no_grace_period__c >0 THEN 'Y' ELSE 'N' END PAST_DUE_IND
,CASE WHEN LLA.Loan__Loan_Status__c='Closed- Written Off' THEN 0 ELSE LLA.loan__Principal_Remaining__c END AS PRIN_OUTSTANDING_AMT
,CASE WHEN LLA.Loan__Loan_Status__c='Closed- Written Off' THEN 0 ELSE LLA.Total_Interest_Accrued__c END AS INTEREST_OUTSTANDING_AMT
,CASE WHEN LLA.Loan__Loan_Status__c='Closed- Written Off' THEN 0 ELSE LLA.loan__Principal_Remaining__c + LLA.Total_Interest_Accrued__c  END AS GROSS_OUTSTANDING_AMT
,LLA.loan__Interest_Rate__c AS INTEREST_RATE
,CASE WHEN A.Credit_Grade__c IN ('SS','DFL','L') THEN 'Y' ELSE 'N' END AS DEFAULTED_IND
,CASE WHEN LLA.DPD_no_grace_period__c IS NOT NULL THEN LLA.DPD_no_grace_period__c ELSE 0 END AS DAYS_PAST_DUE
,LLA.loan__Contractual_Interest_Rate__c AS ORIGINAL_INTEREST_RATE
,CASE WHEN LLA.loan__Last_Installment_Date__c > CURRENT_DATE THEN  DATEDIFF(LLA.loan__Last_Installment_Date__c ,CURRENT_DATE) ELSE 0 END RESIDUAL_MATURITY_DAYS
,CASE WHEN LLA.Loan__Loan_Status__c='Closed- Written Off' THEN 0 ELSE LLA.loan__Principal_Remaining__c END AS INTEREST_BEARING_BALANCE_AMT
,CASE WHEN LLA.loan__Loan_Status__c='Closed- Written Off' THEN LLA.loan__Charged_Off_Principal__c + LLA.loan__Charged_Off_Interest__c + LLA.loan__Charged_Off_Fees__c ELSE 0 END AS WRITEOFF_AMT
,LLA.loan__Last_Payment_Date__c AS LAST_PAYMENT_DATE
,CASE WHEN LLA.loan__Loan_Status__c='Closed - Obligations met' THEN 'CLOSED_OBLIGATIONS_MET'
        WHEN LLA.loan__Loan_Status__c='Active - Good Standing' THEN 'ACTIVE_GOOD_STANDING'
        WHEN LLA.loan__Loan_Status__c='Active - Bad Standing' THEN 'ACTIVE_BAD_STANDING'
        WHEN LLA.loan__Loan_Status__c='Closed- Written Off' THEN 'CLOSED_WRITTEN_OFF'
        WHEN LLA.loan__Loan_Status__c='Canceled' THEN 'CANCELLED'
        ELSE NULL END  AS ACCT_STATUS_CODE
,TIMESTAMPDIFF(MONTH,A.CreatedDate,CURRENT_DATE) AS CUSTOMER_MONTH_ON_BOOK
,CASE WHEN LLA.loan__Frequency_of_Loan_Payment__c='Monthly' THEN LLA.loan__Payment_Amount__c ELSE NULL END AS EMI
,LLA.loan__Principal_Remaining__c  AS DRAWN_AMT
,CASE WHEN A.ParentId IS NOT NULL THEN PA.Credit_Grade__c
    WHEN A.ParentId IS NULL THEN A.Credit_Grade__c
    ELSE '' END AS MAS612_QUALITATIVE_CRITERIA
,LLA.loan__Contractual_Interest_Rate__c  AS EFFECTIVE_INTEREST_RATE
,CASE WHEN A.ParentId IS NOT NULL THEN PA.Customer_days_past_due__c
    WHEN A.ParentId IS NULL THEN A.Customer_days_past_due__c
    ELSE NULL END AS CUSTOMER_DAYS_PAST_DUE
,CASE WHEN LLA.loan__Loan_Status__c LIKE 'Active%' THEN TIMESTAMPDIFF(DAY,loan__Disbursal_Date__c,CURRENT_DATE) ELSE NULL END AS AGE_IN_DAYS
,PLA.Disbursal_Fee_Amount__c AS UPFRONT_PROCESSING_FEE
,CASE WHEN A.UEN_Blacklist_Reason__c IN ('Cease Operations','Financial Crime','Bankrupted','Wound-up') THEN 'A'
      WHEN A.UEN_Blacklist_Reason__c IN ('AML - Internal','Winding-up Suit','Bankruptcy Petition','Credit Litigation') THEN 'B'
      ELSE '' END AS ACCT_BLOCK_CODE
,CASE WHEN P.genesis__CL_Product_Name__c IN ('CVF Low Doc','CVF High Doc','CVF Medium Doc') THEN 'Corporate Vendor Financing' ELSE P.genesis__CL_Product_Name__c END AS BANK_SUB_PRODUCT_CODE 
,CASE WHEN A.Credit_Grade__c IN ('P','SM') THEN 105112
      WHEN A.Credit_Grade__c IN ('DFL','SS','L') THEN 105119
      ELSE NULL END AS GL_ID
,CASE WHEN COALESCE(A.Annual_Sales_Turnover__c,0)  <=100000000 AND A.Individual_Utilization__c  <= 2000000 THEN 'RR' 
		WHEN COALESCE(A.Annual_Sales_Turnover__c,0)  <=100000000 AND A.Individual_Utilization__c  > 2000000 THEN 'SME_CORP' 
ELSE 'CORP' END AS BANK_ASSET_CLASS_CODE
,CASE WHEN P.genesis__CL_Product_Name__c IN ('Working Capital Financing','NIP WC Bullet','Term LN - Citi(Monthly)','Overdraft LN - Citi(Single)') THEN 'N' ELSE 'Y' END AS EXP_REVOLVING_IND
,CASE WHEN LLA.DPD_no_grace_period__c > 60 THEN 'Y' ELSE 'N' END AS HIGH_DPD_CBS_IND
,P.genesis__CL_Product_Name__c AS Product_Code__c
,DATE_FORMAT(DATE(NOW() - INTERVAL 1 MONTH),'%b-%y') AS MonthOfImport
,P.genesis__Maturity_Date__c
,P.Temp_Maturity_Date__c
,GA.Application_Approved_Date__c
FROM NS_Account A
JOIN NS_loan__Loan_Account__c LLA ON A.Id=LLA.loan__Account__c  AND LLA.GXS_Book__c=TRUE 
JOIN NS_genesis__Applications__c GA ON LLA.genesis_app_Id__c=GA.Id
LEFT JOIN NS_genesis__Applications__c P ON GA.genesis__Parent_Application__c=P.Id
LEFT JOIN NS_peer__Loan_Application__c PLA ON PLA.genesis_app_Id__c=GA.Id
LEFT JOIN NS_Account PA ON PA.ID=A.PARENTID -- AND PA.PARENTID IS NOT NULL 
LEFT JOIN Lookup L ON L.SSIC_Code=P.SSIC_Code__c
LEFT JOIN v_CustomerLookup CL ON CL.User_ID__c=A.User_ID__c 
WHERE LLA.loan__Loan_Status__c like 'Active%'
AND LLA.Genesis_Product__c NOT IN ('Term LN - Variable Rate - Monthly') 
AND ( COALESCE(P.Temp_Maturity_Date__c,P.genesis__Maturity_Date__c) < DATE(NOW() - INTERVAL 1 DAY) OR P.genesis__Maturity_Date__c IS NULL)
) CTE;



DROP VIEW IF EXISTS cv_LOAN_DATA_1;
CREATE VIEW cv_LOAN_DATA_1 AS
SELECT C.REPRICING_DATE,C.INTEREST_RATE_TYPE,C.ORIG_LTV,C.CURR_LTV
,C.IMPAIRMENT_STATUS_IND,C.LOAN_PURPOSE_TYPE,C.ULTIMATE_RISK_CPRT,C.LATE_PAYMENT_CHARGES,C.WRITEOFF_DATE,C.TOT_WRITEOFF_QTD,C.ACCOUNT_WRITEOFF_IND
,C.CHANNEL_TYPE,C.GL_PRODUCT,C.GL_CUSTOMER_SEGMENT,C.EXPOSURE_ID,C.REPORTING_DATE,C.CUSTOMER_ID,C.FACILITY_ID,C.EXPOSURE_START_DATE,C.NEXT_PAYMENT_DATE
,C.TXN_CCY_CODE,C.EXPOSURE_END_DATE,C.PAST_DUE_DATE,C.PAST_DUE_IND,C.PRIN_OUTSTANDING_AMT,C.INTEREST_OUTSTANDING_AMT
,C.GROSS_OUTSTANDING_AMT,C.INTEREST_RATE,C.DEFAULTED_IND,C.DAYS_PAST_DUE,C.ORIGINAL_INTEREST_RATE,C.RESIDUAL_MATURITY_DAYS,C.INTEREST_BEARING_BALANCE_AMT
,C.WRITEOFF_AMT,C.LAST_PAYMENT_DATE,C.ACCT_STATUS_CODE,C.CUSTOMER_MONTH_ON_BOOK,C.EMI,C.DRAWN_AMT,C.MAS612_QUALITATIVE_CRITERIA,C.EFFECTIVE_INTEREST_RATE
,C.CUSTOMER_DAYS_PAST_DUE,C.AGE_IN_DAYS,C.UPFRONT_PROCESSING_FEE,C.ACCT_BLOCK_CODE,C.BANK_SUB_PRODUCT_CODE,C.GL_ID,C.BANK_ASSET_CLASS_CODE
,C.EXP_REVOLVING_IND,C.HIGH_DPD_CBS_IND,C.MonthOfImport,C.Application_Approved_Date__c
FROM v_ChildLoan_1 C;




DROP VIEW IF EXISTS v_ChildLoan;
CREATE VIEW v_ChildLoan AS
SELECT DISTINCT 
	REPRICING_DATE
	,INTEREST_RATE_TYPE
	,ORIG_LTV
	,CURR_LTV
	,IMPAIRMENT_STATUS_IND
	,LOAN_PURPOSE_TYPE
	,ULTIMATE_RISK_CPRT
	,LATE_PAYMENT_CHARGES
	,WRITEOFF_DATE
	,TOT_WRITEOFF_QTD
	,ACCOUNT_WRITEOFF_IND
	,CHANNEL_TYPE
	,GL_PRODUCT
	,GL_CUSTOMER_SEGMENT
	,EXPOSURE_ID
	,REPORTING_DATE
	,CUSTOMER_ID
	,FACILITY_ID
	,EXPOSURE_START_DATE
	,NEXT_PAYMENT_DATE
	,TXN_CCY_CODE
	,EXPOSURE_END_DATE
	,PAST_DUE_DATE
	,PAST_DUE_IND
	,PRIN_OUTSTANDING_AMT
	,INTEREST_OUTSTANDING_AMT
	,GROSS_OUTSTANDING_AMT
	,INTEREST_RATE
	,DEFAULTED_IND
	,DAYS_PAST_DUE
	,ORIGINAL_INTEREST_RATE
	,RESIDUAL_MATURITY_DAYS
	,INTEREST_BEARING_BALANCE_AMT
	,WRITEOFF_AMT
	,LAST_PAYMENT_DATE
	,ACCT_STATUS_CODE
	,CUSTOMER_MONTH_ON_BOOK
	,EMI
	,DRAWN_AMT
	,MAS612_QUALITATIVE_CRITERIA
	,EFFECTIVE_INTEREST_RATE
	,CUSTOMER_DAYS_PAST_DUE
	,AGE_IN_DAYS
	,UPFRONT_PROCESSING_FEE
	,ACCT_BLOCK_CODE
	,BANK_SUB_PRODUCT_CODE
	,GL_ID
	,BANK_ASSET_CLASS_CODE
	,EXP_REVOLVING_IND
	,HIGH_DPD_CBS_IND
	,Product_Code__c
	,Application_Approved_Date__c
	,MonthOfImport	
FROM (
SELECT DISTINCT 
CASE WHEN LLA.loan__Interest_Type__c ='Floating' THEN LLA.loan__Floating_Rate_Revision_Date__c ELSE LLA.loan__Last_Installment_Date__c  END AS REPRICING_DATE
,CASE WHEN LLA.loan__Interest_Type__c ='Floating' THEN 'VAR_TYPE' ELSE 'FIX_TYPE' END AS INTEREST_RATE_TYPE
,GA.Percentage_Of_Financed__c AS ORIG_LTV
,GA.Percentage_Of_Financed__c AS CURR_LTV
,CASE WHEN A.Credit_Grade__c IN ('SS','DFL','L') THEN 'Y' ELSE 'N' END AS IMPAIRMENT_STATUS_IND
,CASE WHEN P.genesis__CL_Product_Name__c IN ('Working Capital Financing','NIP WC Bullet','Term LN - Citi(Monthly)','Overdraft LN - Citi(Single)') THEN 'OTH' ELSE 'TF' END AS LOAN_PURPOSE_TYPE
,A.Legal_Entity_Type AS ULTIMATE_RISK_CPRT
,LLA.loan__Fees_Remaining__c + LLA.loan__Fees_Paid__c AS LATE_PAYMENT_CHARGES
,CASE WHEN LLA.Loan__Loan_Status__c='Closed- Written Off' THEN LLA.loan__Charged_Off_Date__c ELSE NULL END AS WRITEOFF_DATE
,CASE WHEN LLA.loan__Loan_Status__c='Closed- Written Off' THEN LLA.loan__Charged_Off_Principal__c + LLA.loan__Charged_Off_Interest__c + LLA.loan__Charged_Off_Fees__c ELSE 0 END AS TOT_WRITEOFF_QTD
,CASE WHEN LLA.Loan__Loan_Status__c='Closed- Written Off' THEN 'Y' ELSE 'N' END AS ACCOUNT_WRITEOFF_IND
,P.Channel__c AS CHANNEL_TYPE
,CASE WHEN P.genesis__CL_Product_Name__c IN ('Working Capital Financing','NIP WC Bullet','Term LN - Citi(Monthly)','Overdraft LN - Citi(Single)') THEN '110230' ELSE '111400' END AS GL_PRODUCT
,CL.GL_Customer_Type_Code AS GL_CUSTOMER_SEGMENT
,LLA.Loan_App_ID__c AS EXPOSURE_ID
,DATE(NOW() - INTERVAL 1 DAY) AS REPORTING_DATE
,A.User_ID__c AS CUSTOMER_ID
,P.Name AS FACILITY_ID
,LLA.loan__Disbursal_Date__c AS EXPOSURE_START_DATE
,CASE WHEN YEAR(LLA.loan__Next_Installment_Date__c)=3000 THEN LLA.loan__Last_Installment_Date__c ELSE LLA.loan__Next_Installment_Date__c END AS NEXT_PAYMENT_DATE
,LLA.Currency__c AS TXN_CCY_CODE
,LLA.loan__Last_Installment_Date__c AS EXPOSURE_END_DATE
,CASE WHEN LLA.DPD_no_grace_period__c >0 THEN LLA.loan__Oldest_Due_Date__c ELSE NULL END PAST_DUE_DATE
,CASE WHEN LLA.DPD_no_grace_period__c >0 THEN 'Y' ELSE 'N' END PAST_DUE_IND
,LLA.loan__Principal_Remaining__c AS PRIN_OUTSTANDING_AMT
,LLA.Total_Interest_Accrued__c AS INTEREST_OUTSTANDING_AMT
,LLA.loan__Principal_Remaining__c + LLA.Total_Interest_Accrued__c  AS GROSS_OUTSTANDING_AMT
,LLA.loan__Interest_Rate__c AS INTEREST_RATE
,CASE WHEN A.Credit_Grade__c IN ('SS','DFL','L') THEN 'Y' ELSE 'N' END AS DEFAULTED_IND
,CASE WHEN LLA.DPD_no_grace_period__c IS NOT NULL THEN LLA.DPD_no_grace_period__c ELSE 0 END AS DAYS_PAST_DUE
,LLA.loan__Contractual_Interest_Rate__c AS ORIGINAL_INTEREST_RATE
,CASE WHEN LLA.loan__Last_Installment_Date__c > CURRENT_DATE THEN  DATEDIFF(LLA.loan__Last_Installment_Date__c ,CURRENT_DATE) ELSE 0 END RESIDUAL_MATURITY_DAYS
,LLA.loan__Principal_Remaining__c AS INTEREST_BEARING_BALANCE_AMT
,CASE WHEN LLA.loan__Loan_Status__c='Closed- Written Off' THEN LLA.loan__Charged_Off_Principal__c + LLA.loan__Charged_Off_Interest__c + LLA.loan__Charged_Off_Fees__c ELSE 0 END AS WRITEOFF_AMT
,LLA.loan__Last_Payment_Date__c AS LAST_PAYMENT_DATE
,CASE WHEN LLA.loan__Loan_Status__c='Closed - Obligations met' THEN 'CLOSED_OBLIGATIONS_MET'
        WHEN LLA.loan__Loan_Status__c='Active - Good Standing' THEN 'ACTIVE_GOOD_STANDING'
        WHEN LLA.loan__Loan_Status__c='Active - Bad Standing' THEN 'ACTIVE_BAD_STANDING'
        WHEN LLA.loan__Loan_Status__c='Closed- Written Off' THEN 'CLOSED_WRITTEN_OFF'
        WHEN LLA.loan__Loan_Status__c='Canceled' THEN 'CANCELLED'
        ELSE NULL END  AS ACCT_STATUS_CODE
,TIMESTAMPDIFF(MONTH,A.CreatedDate,CURRENT_DATE) AS CUSTOMER_MONTH_ON_BOOK
,CASE WHEN LLA.loan__Frequency_of_Loan_Payment__c='Monthly' THEN LLA.loan__Payment_Amount__c ELSE NULL END AS EMI
,LLA.loan__Principal_Remaining__c  AS DRAWN_AMT
,CASE WHEN A.ParentId IS NOT NULL THEN PA.Credit_Grade__c
    WHEN A.ParentId IS NULL THEN A.Credit_Grade__c
    ELSE '' END AS MAS612_QUALITATIVE_CRITERIA
,LLA.loan__Contractual_Interest_Rate__c  AS EFFECTIVE_INTEREST_RATE
,CASE WHEN A.ParentId IS NOT NULL THEN PA.Customer_days_past_due__c
    WHEN A.ParentId IS NULL THEN A.Customer_days_past_due__c
    ELSE NULL END AS CUSTOMER_DAYS_PAST_DUE
,CASE WHEN LLA.loan__Loan_Status__c LIKE 'Active%' THEN TIMESTAMPDIFF(DAY,loan__Disbursal_Date__c,CURRENT_DATE) ELSE NULL END AS AGE_IN_DAYS
,PLA.Disbursal_Fee_Amount__c AS UPFRONT_PROCESSING_FEE
,CASE WHEN A.UEN_Blacklist_Reason__c IN ('Cease Operations','Financial Crime','Bankrupted','Wound-up') THEN 'A'
      WHEN A.UEN_Blacklist_Reason__c IN ('AML - Internal','Winding-up Suit','Bankruptcy Petition','Credit Litigation') THEN 'B'
      ELSE '' END AS ACCT_BLOCK_CODE
,CASE WHEN P.genesis__CL_Product_Name__c IN ('CVF Low Doc','CVF High Doc','CVF Medium Doc') THEN 'Corporate Vendor Financing' ELSE P.genesis__CL_Product_Name__c END AS BANK_SUB_PRODUCT_CODE 
,CASE WHEN A.Credit_Grade__c IN ('P','SM') THEN 105112
      WHEN A.Credit_Grade__c IN ('DFL','SS','L') THEN 105119
      ELSE NULL END AS GL_ID
,CASE WHEN COALESCE(A.Annual_Sales_Turnover__c,0)  <=100000000 AND A.Individual_Utilization__c  <= 2000000 THEN 'RR' 
		WHEN COALESCE(A.Annual_Sales_Turnover__c,0)  <=100000000 AND A.Individual_Utilization__c  > 2000000 THEN 'SME_CORP' 
ELSE 'CORP' END AS BANK_ASSET_CLASS_CODE
,CASE WHEN P.genesis__CL_Product_Name__c IN ('Working Capital Financing','NIP WC Bullet','Term LN - Citi(Monthly)','Overdraft LN - Citi(Single)') THEN 'N' ELSE 'Y' END AS EXP_REVOLVING_IND
,CASE WHEN LLA.DPD_no_grace_period__c > 60 THEN 'Y' ELSE 'N' END AS HIGH_DPD_CBS_IND
,P.genesis__CL_Product_Name__c AS Product_Code__c
,P.genesis__Maturity_Date__c
,P.Temp_Maturity_Date__c
,GA.Application_Approved_Date__c
,DATE_FORMAT(DATE(NOW() - INTERVAL 1 MONTH),'%b-%y') AS MonthOfImport
FROM NS_Account A
JOIN NS_loan__Loan_Account__c LLA ON A.Id=LLA.loan__Account__c  AND LLA.GXS_Book__c=TRUE
JOIN NS_genesis__Applications__c GA ON LLA.genesis_app_Id__c=GA.Id
LEFT JOIN NS_genesis__Applications__c P ON GA.genesis__Parent_Application__c=P.Id
LEFT JOIN NS_peer__Loan_Application__c PLA ON PLA.genesis_app_Id__c=GA.Id
LEFT JOIN NS_Account PA ON PA.ID=A.PARENTID -- AND PA.PARENTID IS NOT NULL 
LEFT JOIN Lookup L ON L.SSIC_Code=P.SSIC_Code__c
LEFT JOIN v_CustomerLookup CL ON CL.User_ID__c=A.User_ID__c
WHERE LLA.loan__Loan_Status__c like 'Active%'
AND LLA.Genesis_Product__c NOT IN ('Term LN - Variable Rate - Monthly')
AND COALESCE(P.Temp_Maturity_Date__c,P.genesis__Maturity_Date__c) >= DATE(NOW() - INTERVAL 1 DAY)
) CTE ;

 

DROP VIEW IF EXISTS cv_LOAN_DATA_2;
CREATE VIEW cv_LOAN_DATA_2 AS
SELECT C.REPRICING_DATE,C.INTEREST_RATE_TYPE,C.ORIG_LTV,C.CURR_LTV
,C.IMPAIRMENT_STATUS_IND,C.LOAN_PURPOSE_TYPE,C.ULTIMATE_RISK_CPRT,C.LATE_PAYMENT_CHARGES,C.WRITEOFF_DATE,C.TOT_WRITEOFF_QTD,C.ACCOUNT_WRITEOFF_IND,C.CHANNEL_TYPE
,C.GL_PRODUCT,C.GL_CUSTOMER_SEGMENT,C.EXPOSURE_ID,C.REPORTING_DATE,C.CUSTOMER_ID,C.FACILITY_ID,C.EXPOSURE_START_DATE,C.NEXT_PAYMENT_DATE,C.TXN_CCY_CODE
,C.EXPOSURE_END_DATE,C.PAST_DUE_DATE,C.PAST_DUE_IND,C.PRIN_OUTSTANDING_AMT,C.INTEREST_OUTSTANDING_AMT,C.GROSS_OUTSTANDING_AMT
,C.INTEREST_RATE,C.DEFAULTED_IND,C.DAYS_PAST_DUE,C.ORIGINAL_INTEREST_RATE,C.RESIDUAL_MATURITY_DAYS,C.INTEREST_BEARING_BALANCE_AMT,C.WRITEOFF_AMT,C.LAST_PAYMENT_DATE
,C.ACCT_STATUS_CODE,C.CUSTOMER_MONTH_ON_BOOK,C.EMI,C.DRAWN_AMT,C.MAS612_QUALITATIVE_CRITERIA,C.EFFECTIVE_INTEREST_RATE,C.CUSTOMER_DAYS_PAST_DUE,C.AGE_IN_DAYS
,C.UPFRONT_PROCESSING_FEE,C.ACCT_BLOCK_CODE,C.BANK_SUB_PRODUCT_CODE,C.GL_ID,C.BANK_ASSET_CLASS_CODE,C.EXP_REVOLVING_IND,C.HIGH_DPD_CBS_IND,C.MonthOfImport,C.Application_Approved_Date__c
FROM v_ChildLoan C;



DROP VIEW IF EXISTS cv_LOAN_DATA;
CREATE VIEW cv_LOAN_DATA AS
SELECT DISTINCT 
REPRICING_DATE
,INTEREST_RATE_TYPE
,ORIG_LTV
,CURR_LTV
,IMPAIRMENT_STATUS_IND
,LOAN_PURPOSE_TYPE
,ULTIMATE_RISK_CPRT
,LATE_PAYMENT_CHARGES
,WRITEOFF_DATE
,TOT_WRITEOFF_QTD
,ACCOUNT_WRITEOFF_IND
,CHANNEL_TYPE
,GL_PRODUCT
,GL_CUSTOMER_SEGMENT
,CTE.EXPOSURE_ID
,CTE.REPORTING_DATE
,CTE.CUSTOMER_ID
,CFD.FACILITY_ID
,EXPOSURE_START_DATE
,NEXT_PAYMENT_DATE
,CTE.TXN_CCY_CODE
,EXPOSURE_END_DATE
,PAST_DUE_DATE
,PAST_DUE_IND
,CFD.LIMIT_COMMITTED_AMT AS SANCTIONED_LIMIT
,CFD.UNDRAWN_AMT 
,PRIN_OUTSTANDING_AMT
,INTEREST_OUTSTANDING_AMT
,GROSS_OUTSTANDING_AMT
,CTE.INTEREST_RATE
,CTE.DEFAULTED_IND
,DAYS_PAST_DUE
,ORIGINAL_INTEREST_RATE
,RESIDUAL_MATURITY_DAYS
,INTEREST_BEARING_BALANCE_AMT
,WRITEOFF_AMT
,LAST_PAYMENT_DATE
,CTE.ACCT_STATUS_CODE
,CTE.CUSTOMER_MONTH_ON_BOOK
,EMI
,DRAWN_AMT
,MAS612_QUALITATIVE_CRITERIA
,EFFECTIVE_INTEREST_RATE
,CUSTOMER_DAYS_PAST_DUE
,AGE_IN_DAYS
,UPFRONT_PROCESSING_FEE
,CTE.ACCT_BLOCK_CODE
,CTE.BANK_SUB_PRODUCT_CODE
,GL_ID
,BANK_ASSET_CLASS_CODE
,EXP_REVOLVING_IND
,HIGH_DPD_CBS_IND
,CTE.MonthOfImport
FROM ( 
SELECT* FROM cv_LOAN_DATA_2
UNION 
SELECT* FROM cv_LOAN_DATA_1
) CTE 
LEFT JOIN CREDIT_FACILITY_DETAILS CFD ON CTE.CUSTOMER_ID =CFD.CUSTOMER_ID AND CTE.BANK_SUB_PRODUCT_CODE =CFD.BANK_SUB_PRODUCT_CODE ;




DROP VIEW IF EXISTS v_LOAN_DATA;
CREATE VIEW v_LOAN_DATA AS 
(
SELECT DISTINCT DATE_FORMAT(REPRICING_DATE, '%Y-%m-%d') AS REPRICING_DATE,ENTITY_CODE,ACCT_CUSTOMER_ROLE,PROJ_FIN_COUNTRY_CODE,PROJ_FIN_SUB_SECTOR,UNCONDITIONAL_CANCEL_IND,
UNSECURED_IND,ORIG_LTV,CURR_LTV,INTEREST_RATE_TYPE,BRANCH_ID,DATA_SOURCE,IMPAIRMENT_STATUS_IND,RESTRUCTURED_IND,LOAN_PURPOSE_TYPE,SYNDICATED_AMT,SYNDICATED_IND,ACT_LEAD_ARRANGER_IND,
LEAD_ARRANGER_AMT,IFRS9_CLASS_TYPE,ULTIMATE_RISK_CPRT,FAIRVALUE_HIER,BOOK_TYPE,INT_RATE_SENSITIVE_IND,PLEDGED_AMT,FORECLOSED_IND,transactor_ind,FREE_CREDIT_BALANCE_AMT,INTEREST_CHARGES,
BANK_CHARGES,LATE_PAYMENT_CHARGES,ACTION_INITIATED_IND,ACTION_INITIATED_TYPE,TRANSITIONAL_ARRANGEMENT_IND,DATE_FORMAT(WRITEOFF_DATE, '%Y-%m-%d') AS WRITEOFF_DATE,TOT_WRITEOFF_QTD,
ACCOUNT_WRITEOFF_IND,SUSPENSION_IND,GEN_ALLOWANCE_AMT,BANK_ASSET_CLASS_CODE,MARKET_VALUE,EXP_REVOLVING_IND,CHANNEL_TYPE,MATERIALITY_THRESHOLD,NOMINAL_THRESHOLD,ENCUMBRANCE_STATUS_IND,
POCI_IND,GL_DEPARTMENT,GL_LOB,GL_LOCATION,GL_INTERCOMPANY,GL_PRODUCT,GL_CUSTOMER_SEGMENT,GL_FUTURE1,GL_FUTURE2,UNUSED_LIMIT,JUNIOR_CHARGE_IND,EXPOSURE_ID,
DATE_FORMAT(REPORTING_DATE, '%Y-%m-%d') AS REPORTING_DATE,CUSTOMER_ID,FACILITY_ID,DATE_FORMAT(EXPOSURE_START_DATE, '%Y-%m-%d') AS EXPOSURE_START_DATE,
DATE_FORMAT(NEXT_PAYMENT_DATE, '%Y-%m-%d') AS NEXT_PAYMENT_DATE,BANK_PRODUCT_CODE,TXN_CCY_CODE,COUNTRY_CODE,DATE_FORMAT(EXPOSURE_END_DATE, '%Y-%m-%d') AS EXPOSURE_END_DATE,
DATE_FORMAT(PAST_DUE_DATE, '%Y-%m-%d') AS PAST_DUE_DATE,PAST_DUE_IND,SANCTIONED_LIMIT,PRIN_OUTSTANDING_AMT,INTEREST_OUTSTANDING_AMT,GROSS_OUTSTANDING_AMT,UNDRAWN_AMT,INTEREST_RATE,
DEFAULTED_IND,DATE_FORMAT(RESTRUCTURED_DATE, '%Y-%m-%d') AS RESTRUCTURED_DATE,EXTENDED_CREDIT_FAC_IND,DAYS_PAST_DUE,ULTIMATE_RISK_COUNTRY,ORIGINAL_INTEREST_RATE,RESIDUAL_MATURITY_DAYS,
INTEREST_BEARING_BALANCE_AMT,AGE_IN_DAYS,WRITEOFF_AMT,ACCOUNT_MAS635_IND,DATE_FORMAT(LAST_PAYMENT_DATE, '%Y-%m-%d') AS LAST_PAYMENT_DATE,ACCT_STATUS_CODE,
DATE_FORMAT(ACCT_STATUS_DATE, '%Y-%m-%d') AS ACCT_STATUS_DATE,GL_ID,CUSTOMER_MONTH_ON_BOOK,EMI,DRAWN_AMT,MAS612_QUALITATIVE_CRITERIA,HIGH_DPD_CBS_IND,MINIMUM_PAYMENT_IND,
CUSTOMER_DAYS_PAST_DUE,DPD_COUNT_EXCEEDED,HAS_ACCELERATED_LOANS,INDEFINITE_BLOCK_DPD_COUNT_EXCEEDED,SUSPENDED_BTI_FLAG,CBS_CUO,EFFECTIVE_INTEREST_RATE,UPFRONT_PROCESSING_FEE,
UPFRONT_UNAMORTIZE_FEE,ACCT_BLOCK_CODE,BANK_SUB_PRODUCT_CODE,CONVERSION_TYPE,MonthOfImport
FROM LOAN_DATA
WHERE MonthOfImport=DATE_FORMAT(DATE(NOW() - INTERVAL 1 MONTH),'%b-%y') 
ORDER BY CUSTOMER_ID,FACILITY_ID
);	



DROP PROCEDURE IF EXISTS proc_LoanData;
DELIMITER $$
CREATE DEFINER=`sg_automation`@`%` PROCEDURE `proc_LoanData`(IN IN_JOB_ID INT)
mainBlock:BEGIN
/*******************************************************
** File: proc_LoanData
** Name: LOAN_DATA
** Desc: DM - LoanData
** Auth: Vivek Srinivasamorthy
** Date: 28-01-2025
*******************************************************
** Change History
*******************************************************
** PR   Date        Author  Description 
** --   --------   -------   -------------------
** 1    
*******************************************************/
    DECLARE LV_TABLE_NAME,LV_STATUS VARCHAR(255);
    DECLARE ErrorMessage TEXT DEFAULT '';
    DECLARE done BOOLEAN;
    DECLARE LSQL TEXT DEFAULT '';
    DECLARE l_code VARCHAR(5) DEFAULT '';
    DECLARE l_message TEXT DEFAULT '';
    DECLARE l_rowcount INT DEFAULT NULL;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        GET DIAGNOSTICS CONDITION 1
        l_code = returned_sqlstate,
        l_message = message_text;
        CALL error_handler('Error',
        'An Exception Occured',
        l_code,
        CONCAT(l_message, " ---while running-", COALESCE(@LSQL, '')),
        'proc_LoanData'
        ,CONCAT(IN_JOB_ID));
    END;
    
    SET LV_TABLE_NAME= 'LOAN_DATA';

    CALL sys.table_exists(DATABASE(), LV_TABLE_NAME,@exist); 

    SET SQL_SAFE_UPDATES = 0;
  
    SET LSQL='',l_code='',l_message='', l_rowcount=0;
    SET LSQL = CONCAT("DELETE FROM ",LV_TABLE_NAME," WHERE MonthOfImport = CONCAT(DATE_FORMAT(DATE(NOW() - INTERVAL 4 MONTH),'%b'),'-',DATE_FORMAT(DATE(NOW() - INTERVAL 4 MONTH),'%y') )");   
    SET @LSQL = LSQL;
    PREPARE STMT2 FROM @LSQL;
    EXECUTE STMT2;
    GET DIAGNOSTICS l_rowcount = ROW_COUNT;
    DEALLOCATE PREPARE STMT2; 
    
    IF l_code=''
    THEN
        CALL error_handler(
        'Info',
        'Success',
        '',
        CONCAT("Table: ",LV_TABLE_NAME," - Deleted Month: ",DATE_FORMAT(DATE(NOW() - INTERVAL 4 MONTH),'%b-%y')," counts:",l_rowcount),
        'proc_LoanData'
        ,CONCAT(IN_JOB_ID));
    END IF; 

    SET LSQL='',l_code='',l_message='', l_rowcount=0, @LV_ACTIVE_MONTH=0, @LV_MonthOfImport=CONCAT(DATE_FORMAT(DATE(NOW() - INTERVAL 1 MONTH),'%b'),'-',DATE_FORMAT(DATE(NOW() - INTERVAL 1 MONTH),'%y') );
    SET LSQL = CONCAT("SELECT COUNT(*) INTO @LV_ACTIVE_MONTH FROM ",LV_TABLE_NAME," WHERE MonthOfImport = '",@LV_MonthOfImport,"';");   
    SET @LSQL = LSQL;
    PREPARE STMT2 FROM @LSQL;
    EXECUTE STMT2;
    DEALLOCATE PREPARE STMT2; 
    
    IF l_code='' AND @LV_ACTIVE_MONTH>0
    THEN
        CALL error_handler(
        'Info',
        'Success',
        '',
        CONCAT("Table: ",LV_TABLE_NAME," - Already Exists: ",DATE_FORMAT(DATE(NOW() - INTERVAL 1 MONTH),'%b-%y')," counts:",@LV_ACTIVE_MONTH),
        'proc_LoanData'
        ,CONCAT(IN_JOB_ID));
        SET LV_STATUS = 'Warning';
        LEAVE mainBlock;
    END IF;  
   
    START TRANSACTION;

    SET LSQL='',l_code='',l_message='', l_rowcount=0;
    SET LSQL = CONCAT("INSERT INTO ",LV_TABLE_NAME,"
                        (UNDRAWN_AMT,REPRICING_DATE,INTEREST_RATE_TYPE,ORIG_LTV,CURR_LTV,IMPAIRMENT_STATUS_IND,LOAN_PURPOSE_TYPE,ULTIMATE_RISK_CPRT,
						LATE_PAYMENT_CHARGES,WRITEOFF_DATE,TOT_WRITEOFF_QTD,ACCOUNT_WRITEOFF_IND,CHANNEL_TYPE,GL_PRODUCT,GL_CUSTOMER_SEGMENT,EXPOSURE_ID,REPORTING_DATE,CUSTOMER_ID,FACILITY_ID,EXPOSURE_START_DATE,
						NEXT_PAYMENT_DATE,TXN_CCY_CODE,EXPOSURE_END_DATE,PAST_DUE_DATE,PAST_DUE_IND,SANCTIONED_LIMIT,PRIN_OUTSTANDING_AMT,INTEREST_OUTSTANDING_AMT,GROSS_OUTSTANDING_AMT,INTEREST_RATE,DEFAULTED_IND,
						DAYS_PAST_DUE,ORIGINAL_INTEREST_RATE,RESIDUAL_MATURITY_DAYS,INTEREST_BEARING_BALANCE_AMT,WRITEOFF_AMT,LAST_PAYMENT_DATE,ACCT_STATUS_CODE,CUSTOMER_MONTH_ON_BOOK,EMI,DRAWN_AMT,MAS612_QUALITATIVE_CRITERIA,
						EFFECTIVE_INTEREST_RATE,CUSTOMER_DAYS_PAST_DUE,AGE_IN_DAYS,UPFRONT_PROCESSING_FEE,ACCT_BLOCK_CODE,BANK_SUB_PRODUCT_CODE,GL_ID,BANK_ASSET_CLASS_CODE,EXP_REVOLVING_IND,HIGH_DPD_CBS_IND,MonthOfImport)
                        SELECT DISTINCT UNDRAWN_AMT,REPRICING_DATE,INTEREST_RATE_TYPE,ORIG_LTV,CURR_LTV,IMPAIRMENT_STATUS_IND,LOAN_PURPOSE_TYPE,ULTIMATE_RISK_CPRT,
						LATE_PAYMENT_CHARGES,WRITEOFF_DATE,TOT_WRITEOFF_QTD,ACCOUNT_WRITEOFF_IND,CHANNEL_TYPE,GL_PRODUCT,GL_CUSTOMER_SEGMENT,EXPOSURE_ID,REPORTING_DATE,CUSTOMER_ID,FACILITY_ID,EXPOSURE_START_DATE,
						NEXT_PAYMENT_DATE,TXN_CCY_CODE,EXPOSURE_END_DATE,PAST_DUE_DATE,PAST_DUE_IND,SANCTIONED_LIMIT,PRIN_OUTSTANDING_AMT,INTEREST_OUTSTANDING_AMT,GROSS_OUTSTANDING_AMT,INTEREST_RATE,DEFAULTED_IND,
						DAYS_PAST_DUE,ORIGINAL_INTEREST_RATE,RESIDUAL_MATURITY_DAYS,INTEREST_BEARING_BALANCE_AMT,WRITEOFF_AMT,LAST_PAYMENT_DATE,ACCT_STATUS_CODE,CUSTOMER_MONTH_ON_BOOK,EMI,DRAWN_AMT,MAS612_QUALITATIVE_CRITERIA,
						EFFECTIVE_INTEREST_RATE,CUSTOMER_DAYS_PAST_DUE,AGE_IN_DAYS,UPFRONT_PROCESSING_FEE,ACCT_BLOCK_CODE,BANK_SUB_PRODUCT_CODE,GL_ID,BANK_ASSET_CLASS_CODE,EXP_REVOLVING_IND,HIGH_DPD_CBS_IND,MonthOfImport
                        FROM  cv_",LV_TABLE_NAME,";");   
    SET @LSQL = LSQL;
    PREPARE STMT2 FROM @LSQL;
    EXECUTE STMT2;
    GET DIAGNOSTICS l_rowcount = ROW_COUNT;
    DEALLOCATE PREPARE STMT2; 
    
    COMMIT;
    
    IF l_code=''
    THEN
        SET LV_STATUS = 'Completed';
        CALL error_handler(
        'Info',
        'Success',
        '',
        CONCAT("Table: ",LV_TABLE_NAME," - Inserted Month: ",DATE_FORMAT(DATE(NOW() - INTERVAL 1 MONTH),'%b-%y')," counts:",l_rowcount),
        'proc_LoanData'
        ,CONCAT(IN_JOB_ID));
    ELSE
        SET LV_STATUS = 'Error';
    END IF; 

    SET LSQL='',l_code='',l_message='';
    SET LSQL = CONCAT("UPDATE NS_Job_Detail SET RowCount=",l_rowcount,",Status='",LV_STATUS,"',EndDateTime=NOW() WHERE JobID=",IN_JOB_ID," AND NS_Name='",LV_TABLE_NAME,"';");   
    SET @LSQL = LSQL;
    PREPARE STMT2 FROM @LSQL;
    EXECUTE STMT2;
    GET DIAGNOSTICS l_rowcount = ROW_COUNT;
    DEALLOCATE PREPARE STMT2; 

    IF l_code=''
    THEN
        CALL error_handler(
        'Info',
        'Success',
        '',
        CONCAT("Table: NS_Job_Detail - Updated RowCount Successfully"),
        'proc_LoanData'
        ,CONCAT(IN_JOB_ID));
    END IF; 
END$$
DELIMITER ;
